### PR TITLE
Swap xUnit with Nunit

### PR DESCRIPTION
**Pull request by jplebre**
This is a preference thing, I'm not fussed either way but since I was cleaning up the solution a bit decided to do that. Seems that we in house generally prefer xUnit so why not keep with the conventions?

### CODE REVIEW

**Comment by slang25** [comment]
You say prefer xUnit, but I think you mean NUnit. I think in the .NET open source eco-system, more people are moving to xUnit, for example Microsoft (that's not a good reason in itself of course), I think this is due to it having earlier and better support for dotnet core and core test runners.

Given this is an open source project I would be inclined to vote against this, just an opinion of course.

**Comment by JosephWoodward** [comment]
I would agree with @slang25 here. NUnit has been somewhat slow in migrating to .NET Standard meaning testing has been difficult in libraries using NUnit (which is why a lot of people migrated to xUnit).

**Comment by jplebre** [comment]
Not really fussed either way, but since nunit can run in .net core and we use it almost exclusively internally seemed to make some sense.

As mentioned above, took me only a few minutes to do since I was here anyway, feel free to close.

It will be harder to swap everything in JE to xunit, and I'm a sucker for consistency :)

**Comment by AnthonySteele** [comment]
Looks good to me. Nobody needs *both* nunit and xunit in order to run some tests, lets pick *one*. I'm more familair with NUnit but that's of lesser importance.

**Comment by skewwhiffy** [comment]
I think some valid points have been made for xUnit, but I recks the two pertinent facts are:
- Why change it, if it ain't broke?
- xunit has historically been a little faster at moving with the flow of things, for instance with .NET core.

I'm therefore inclined to decline this PR as the path of least resistence, as well as there being no obvious advantage to using nunit over xunit.

@jplebre What do you think?

**Comment by AnthonySteele** [comment]
The only way that I would decline this PR, was if there was commitment to remove NUnit from this project and only use xUnit. Having both testing frameworks is worse than having either.

**Comment by slang25** [comment]
I hadn't appreciated that we had both, yeah that sucks 😄
I've submitted #44, so we can go either way. I agree, we need to go one way or the other.

**Comment by jplebre** [comment]
My only argument was that internally afaik on the components we work w we use nunit a lot more often than xunit. I prefer nunit but that's just me :)

It is correct xunit right now is first citizen on .net core, but both work on the new releases

**Comment by AnthonySteele** [comment]
Pick one of https://github.com/justeat/JustFakeIt/pull/44 and https://github.com/justeat/JustFakeIt/pull/41, merge it and close the other one.

**Comment by skewwhiffy** [comment]
I'm going to close this one in favour of https://github.com/justeat/JustFakeIt/pull/44 unless I hear objections.

**Pull request closed without merging**
